apiVersion: v1
kind: ConfigMap

metadata:
  name: monitoring-config

data:
  INFERENCE_SERVICE_URL: "http://inference-service:8000/predict"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "churndb"